services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'      
          memory: 2g
        reservations:
          cpus: '0.2'
          memory: 1g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s  
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: meetingroombooking
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    deploy:
      resources:
          limits:
            cpus: '0.4'
            memory: 2g
          reservations:
            cpus: '0.2'
            memory: 1g

volumes:
  mysql_data:
